AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "test/**/*"
